/**
 * Openapi specification - Darshan
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: walnut2918@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthenticateRequest from './model/AuthenticateRequest';
import AuthenticateResponse from './model/AuthenticateResponse';
import BorrowedNotesResponse from './model/BorrowedNotesResponse';
import FeedBackRequest from './model/FeedBackRequest';
import FeedBackResponse from './model/FeedBackResponse';
import NotesRequest from './model/NotesRequest';
import NotesResponse from './model/NotesResponse';
import PageResponseBorrowedNotesResponse from './model/PageResponseBorrowedNotesResponse';
import PageResponseFeedBackResponse from './model/PageResponseFeedBackResponse';
import PageResponseNotesResponse from './model/PageResponseNotesResponse';
import RegistrationRequest from './model/RegistrationRequest';
import AuthenticationApi from './api/AuthenticationApi';
import FeedbacksApi from './api/FeedbacksApi';
import NotesApi from './api/NotesApi';


/**
* OpenApi documentation for Spring security.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenapiSpecificationDarshan = require('index'); // See note below*.
* var xxxSvc = new OpenapiSpecificationDarshan.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenapiSpecificationDarshan.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenapiSpecificationDarshan.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenapiSpecificationDarshan.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthenticateRequest model constructor.
     * @property {module:model/AuthenticateRequest}
     */
    AuthenticateRequest,

    /**
     * The AuthenticateResponse model constructor.
     * @property {module:model/AuthenticateResponse}
     */
    AuthenticateResponse,

    /**
     * The BorrowedNotesResponse model constructor.
     * @property {module:model/BorrowedNotesResponse}
     */
    BorrowedNotesResponse,

    /**
     * The FeedBackRequest model constructor.
     * @property {module:model/FeedBackRequest}
     */
    FeedBackRequest,

    /**
     * The FeedBackResponse model constructor.
     * @property {module:model/FeedBackResponse}
     */
    FeedBackResponse,

    /**
     * The NotesRequest model constructor.
     * @property {module:model/NotesRequest}
     */
    NotesRequest,

    /**
     * The NotesResponse model constructor.
     * @property {module:model/NotesResponse}
     */
    NotesResponse,

    /**
     * The PageResponseBorrowedNotesResponse model constructor.
     * @property {module:model/PageResponseBorrowedNotesResponse}
     */
    PageResponseBorrowedNotesResponse,

    /**
     * The PageResponseFeedBackResponse model constructor.
     * @property {module:model/PageResponseFeedBackResponse}
     */
    PageResponseFeedBackResponse,

    /**
     * The PageResponseNotesResponse model constructor.
     * @property {module:model/PageResponseNotesResponse}
     */
    PageResponseNotesResponse,

    /**
     * The RegistrationRequest model constructor.
     * @property {module:model/RegistrationRequest}
     */
    RegistrationRequest,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The FeedbacksApi service constructor.
    * @property {module:api/FeedbacksApi}
    */
    FeedbacksApi,

    /**
    * The NotesApi service constructor.
    * @property {module:api/NotesApi}
    */
    NotesApi
};
