/**
 * Openapi specification - Darshan
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: walnut2918@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FeedBackRequest model module.
 * @module model/FeedBackRequest
 * @version 1.0
 */
class FeedBackRequest {
    /**
     * Constructs a new <code>FeedBackRequest</code>.
     * @alias module:model/FeedBackRequest
     * @param comment {String} 
     * @param noteId {Number} 
     */
    constructor(comment, noteId) { 
        
        FeedBackRequest.initialize(this, comment, noteId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, comment, noteId) { 
        obj['comment'] = comment;
        obj['noteId'] = noteId;
    }

    /**
     * Constructs a <code>FeedBackRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeedBackRequest} obj Optional instance to populate.
     * @return {module:model/FeedBackRequest} The populated <code>FeedBackRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeedBackRequest();

            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('noteId')) {
                obj['noteId'] = ApiClient.convertToType(data['noteId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FeedBackRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FeedBackRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FeedBackRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }

        return true;
    }


}

FeedBackRequest.RequiredProperties = ["comment", "noteId"];

/**
 * @member {Number} note
 */
FeedBackRequest.prototype['note'] = undefined;

/**
 * @member {String} comment
 */
FeedBackRequest.prototype['comment'] = undefined;

/**
 * @member {Number} noteId
 */
FeedBackRequest.prototype['noteId'] = undefined;






export default FeedBackRequest;

