/**
 * Openapi specification - Darshan
 * OpenApi documentation for Spring security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: walnut2918@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NotesResponse from './NotesResponse';

/**
 * The PageResponseNotesResponse model module.
 * @module model/PageResponseNotesResponse
 * @version 1.0
 */
class PageResponseNotesResponse {
    /**
     * Constructs a new <code>PageResponseNotesResponse</code>.
     * @alias module:model/PageResponseNotesResponse
     */
    constructor() { 
        
        PageResponseNotesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageResponseNotesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageResponseNotesResponse} obj Optional instance to populate.
     * @return {module:model/PageResponseNotesResponse} The populated <code>PageResponseNotesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageResponseNotesResponse();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [NotesResponse]);
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('totalElement')) {
                obj['totalElement'] = ApiClient.convertToType(data['totalElement'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('first')) {
                obj['first'] = ApiClient.convertToType(data['first'], 'Boolean');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageResponseNotesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageResponseNotesResponse</code>.
     */
    static validateJSON(data) {
        if (data['content']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['content'])) {
                throw new Error("Expected the field `content` to be an array in the JSON data but got " + data['content']);
            }
            // validate the optional field `content` (array)
            for (const item of data['content']) {
                NotesResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/NotesResponse>} content
 */
PageResponseNotesResponse.prototype['content'] = undefined;

/**
 * @member {Number} number
 */
PageResponseNotesResponse.prototype['number'] = undefined;

/**
 * @member {Number} size
 */
PageResponseNotesResponse.prototype['size'] = undefined;

/**
 * @member {Number} totalElement
 */
PageResponseNotesResponse.prototype['totalElement'] = undefined;

/**
 * @member {Number} totalPages
 */
PageResponseNotesResponse.prototype['totalPages'] = undefined;

/**
 * @member {Boolean} first
 */
PageResponseNotesResponse.prototype['first'] = undefined;

/**
 * @member {Boolean} last
 */
PageResponseNotesResponse.prototype['last'] = undefined;






export default PageResponseNotesResponse;

