spring:
    application:
        name: apigateway

    config:
      import: optional:configserver:http://localhost:8085

    cloud:
      gateway:
        routes:
          - id: USERSERVICE
            uri: lb://USERSERVICE
            predicates:
              - Path=/users/**

          - id: RATINGSERVICE
            uri: lb://RATINGSERVICE
            predicates:
            - Path=/ratings/**

          - id: HOTELSERVICE
            uri: lb://HOTELSERVICE
            predicates:
            - Path=/hotels/**,/staffs/**
        discovery:
          locator:
            enabled: true
        
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE

    

server:
  port: 8080



# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix: DEBUG



