spring:
    application:
        name: api-gateway

    cloud:
        gateway:
            routes:
                #  http://localhost:4004/auth/login
                ## API GATEWAY -> http://auth-service:4005/login 
                - id: auth-service-route
                  uri: http://host.docker.internal:4005
                  predicates:
                    - Path=/auth/**
                  filters:
                    - StripPrefix=1

                ## REST CLIENT -> http://localhost:4004/api/patients
                ## API GateWAY -> http://patient-service:4000/patients
                ## PATIENT SERVICE (SPRINGBOOT APP) -> /patients -> Patient Array
                - id: patient-service-route
                  uri: http://host.docker.internal:4000
                  predicates:
                    - Path=/api/patients/**
                  filters:
                    - StripPrefix=1
                    - JwtValidate

                ## REST CLIENT -> http://localhost:4004/api-docs/patients
                ## API GateWAY -> http://patient-service:4000/v3/api-docs
                - id: api-docs-patient-route
                  uri: http://host.docker.internal:4000
                  predicates:
                    - Path=/api-docs/patients
                  filters:
                    - RewritePath=/api-docs/patients,/v3/api-docs

                - id: api-docs-auth-route
                  uri: http://host.docker.internal:4005
                  predicates:
                    - Path=/api-docs/auth
                  filters:
                    - RewritePath=/api-docs/auth,/v3/api-docs

    
server:
    port: 4004
