spring:
    application:
        name: uploadtoawss3
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB


amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: XXXXXXXXXXXXXXXXX
  secretKey: XXXXXXXXXXXXXXXXXXXXXXXXXX
  bucketName: your-bucket-name

aws:
  region: your region
